### ISSUE TITLE
Failed to find plugin node-express

### ISSUE THREAD

**Issue by VorT3x** [angelozerr/tern-node-express#12]
Doesn't work on node v0.12.2

Installed it globally & locally, but still got this error: 
```
atom-ternjs
Failed to find plugin node-express.
```

```json
Config:

{
  "exclude": ["node_modules/**"],
  "libs": [
    "browser",
    "ecma5",
    "ecma6",
    "jquery"
  ],
  "plugins": {
    "complete_strings": {},
    "node": {},
    "node-express": {},
    "lint": {},
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

**Comment by angelozerr** [comment]
That's very strange? If you try to copy the node-express.js inside tern/plugins folder, is it working?

**Comment by VorT3x** [comment]
Found a problem, I'm using atom-ternjs plugin for Atom, but installed node-express plugin into my project, but not into atom-ternjs folder: ~/.atom/packages/atom-ternjs

And -g didn't help :)

So it's not a bug :+1:
