### ISSUE TITLE
Can't get node and node-express to work together in the same .tern-project

### ISSUE THREAD

**Issue by thalesmello** [angelozerr/tern-node-express#13]
I followed the install instructions in order to set up my project. The problem is that, it I try to use the suggested `.tern-project` file in my project, such as below, I don't get autocomplete for express.

	{
	  "plugins": {
	    "node": {},
	    "node-express": {}
	  }
	}

However, it I put "node-express" before the "node" plugin, suddenly everything works well.

	{
	  "plugins": {
	    "node-express": {},
	    "node": {}
	  }
	}

Is it supposed to work this way?

**Comment by thalesmello** [comment]
Actually, pardon me. The information provided above is incorrect.

I can't get `node` and `node-express` plugins to work together. The following `.tern-project` will give me autocomplete and documentation for express, but I need node auto complete as well.

{
  "plugins": {
    "node-express": {}
  }
}

**Comment by angelozerr** [comment]
@thalesmello if you are using tern > 0.13.0 (like 0.15.0), it seems tern-node-express doesn't work. I have created an issue for that https://github.com/marijnh/tern/issues/641

**Comment by angelozerr** [comment]
Parhaps it's teh same issue than https://github.com/angelozerr/tern-node-express/issues/14?

**Comment by angelozerr** [comment]
@thalesmello I have published node-express which uses now tern 0.16.0. Could you retry please?

**Comment by thalesmello** [comment]
@angelozerr I've tested and it's working correctly. Thank you for your support.

**Comment by angelozerr** [comment]
Thanks for hgaing done test. I close this issue.
